TOP := ..

TARGET := libstm32startup

SOURCES += startup.c
SOURCES += tag.c

LOCAL_CFLAGS += -I$(TOP)/include -I$(TOP)/stm32-platform -I$(TOP)/rtthread-nano -I$(TOP)/rtthread-nano/include -I$(TOP)/cutils/include

include $(TOP)/Makefile.include
