#!/bin/bash

export BUILD_PLATFORM_ID=STM32L475
export BUILD_PLATFORM_CHIP=STM32L475VET6
export LDSCRIPTS_PATH=STM32L475VETx_FLASH.ld
export ARM_CPU_ARCH=cortex-m4

export SUPPORT_STM32_ASSERT=1

bash ../build_stm32.sh $BUILD_PLATFORM_ID
