#!/bin/bash

export ROOT_PATH=$PWD/../..
export EXTERN_DEFINED="-DBUILD_CHIP_${BUILD_PLATFORM_CHIP} "

if [ -z $STM32_SUPPORT_SAMPLE ]; then
export STM32_SUPPORT_SAMPLE=0
fi

if [ -z $SUPPORT_STM32_ASSERT ]; then
export SUPPORT_STM32_ASSERT=0
fi

if [ -z $SDK_RELEASE ]; then
export SDK_RELEASE=0
fi 

if [ $SUPPORT_STM32_ASSERT -eq 1 ]; then
export EXTERN_DEFINED="$EXTERN_DEFINED -DUSE_STM32_ASSERT "
fi

if [ $SDK_RELEASE -eq 1 ]; then
export EXTERN_DEFINED="$EXTERN_DEFINED -DSDK_RELEASE "
fi

export EXTERN_DEFINED="$EXTERN_DEFINED -DSTM32_TAG_ADDR=${STM32_TAG_ADDR} "
export EXTERN_DEFINED="$EXTERN_DEFINED -DSTM32_TAG_SIZE=${STM32_TAG_SIZE} "
