TOP := ..

TARGET := libcutils

SOURCES += src/retarget.c
SOURCES += src/properties.c

LOCAL_CFLAGS += -I$(TOP)/include -I$(TOP)/stm32-platform -I$(TOP)/cutils/include

include $(TOP)/Makefile.include
